### ISSUE TITLE
Bug: Lighting an Unlit Wall Torch crashes the game

### ISSUE THREAD

**Issue by Andrew6rant** [realguyman/totally_lit#9]
Using an item with the `torch_igniters` tag on a wall-mounted torch causes the game to crash. This does not occur with flint and steel.

For the longest time I thought this issue was a bug with my Teeny Coal compatibility fork, but it looks like it is an upstream thing, haha.

Tested with 0.9.1 and 0.9.0

<details>
<summary>Show stacktrace:</summary>
java.lang.IllegalArgumentException: Cannot get property class_2753{name=facing, clazz=class net.minecraft.class_2350, values=[north, east, south, west, up, down]} as it does not exist in Block{totally_lit:unlit_wall_torch}
	at net.minecraft.class_2688.method_11654(class_2688.java:98) ~[client-intermediary.jar:?]
	at io.github.realguyman.totally_lit.block.UnlitWallTorchBlock.method_9534(UnlitWallTorchBlock.java:32) ~[totally_lit-0.9.1+1.18.2.jar:?]
	at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:939) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_2896(class_636.java:320) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1583(class_310.java:1659) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:1912) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1739) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1091) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:737) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
</details>

**Comment by realguyman** [comment]
I'll have this fixed and released today.

**Comment by realguyman** [comment]
Fixed in 0.9.2. Thanks for reporting this bug!
